name: Publish
on: 
  release:
   types: [published]

jobs:
  publish-npmjs:
    permissions:
      packages: write
      contents: read
    uses: millicast/github-actions/.github/workflows/npm-publish.yml@main
    with:
      registry-url: 'https://registry.npmjs.org/'
    secrets:
      token: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
